### ISSUE TITLE
v25 - /run.sh: line 148: null: unbound variable

### ISSUE THREAD

**Issue by ZeroHour** [adamoutler/HassOSArgonOneAddon#32] opened 2022-06-19 23:10 UTC
Hi
I just updated to v25 from the older v24 version and its now getting the below error.
This is on a Pi4b 8GB.

I realise your iterating quite quickly today but I thought I would report it.

Cheers and thanks for keeping this going!

```
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- 1a -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Settings initialized. Argon One Detected. Beginning monitor..
Failed 1: value_a=$((100/(tmaxi-tmini)))
/run.sh: line 148: null: unbound variable
Safe Mode Activated!
[cmd] /run.sh exited 1
```

The config YAML

```
ManageStyle: Step
CorF: C
LowRange: 44
MediumRange: 48
HighRange: 55
QuietProfile: false
Create a Fan Speed entity in Home Assistant: false
Log current temperature every 30 seconds: true
```

**Comment by bschollnick** [comment] 2022-06-19 23:14
Just ran into this as well.  

And for some reason the ArgonOne Fanspeed sensor has disappeared (presumably since the script isn't starting up properly?).

**Comment by charles** [comment] 2022-06-19 23:20
Same problem:

``` 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 25
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.6.6
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- 1a -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Settings initialized. Argon One Detected. Beginning monitor..
Failed 1: value_a=$((100/(tmaxi-tmini)))
/run.sh: line 148: null: unbound variable
Safe Mode Activated!
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by ZeroHour** [comment] 2022-06-19 23:20
Yeah it seems to be calling the Linear script even though we are using the Step option. Just having a play.

**Comment by ZeroHour** [comment] 2022-06-19 23:25
If you stop the ArgonOne Active Cooling addon and install the new ArgonOne Active Linear Cooling and run and configure that it will get your fans under control until the existing addon is fixed.

I would not remove the existing one until the dev tells us.

**Comment by FreelancerJay** [comment] 2022-06-20 02:09
The linear script is only being called if your "ManageStyle" config option is set to linear... It seems that the script is failing earlier than that if/else statement though.
I tried changing the setting to linear in the config options but am getting the same unbound variable failure, just for troubleshooting note.

That said my Pi is now running cooler, since the add-on enabled safe mode correctly and left the fan running 100% before terminating, so at least the safeties in here seem to be working correctly. Since the occupant of the room with my Pi in it is currently away, I'ma just leave it like that since the noise won't bother anyone :-)

**Comment by karanvivekbhargava** [comment] 2022-06-20 04:08
Facing the same issue. Just started using the component - awesome work :). Commenting to increase urgency.

**Comment by adamoutler** [comment] 2022-06-20 04:25
I'm having problems reproducing.   I'd recommend uninstalling and reinstalling, as well as setting defaults. 
![Screenshot_20220620-002411](https://user-images.githubusercontent.com/527919/174525033-17f94ad4-108e-46f4-bcc1-c7520ae9150f.png)

**Comment by FreelancerJay** [comment] 2022-06-20 04:31
Is there anything I can do to have the logging more verbose to help in troubleshooting this?

**Comment by adamoutler** [comment] 2022-06-20 04:36
No.  I just realized I had caused a bad merge.   The original plan was to merge the linear version into the standard version, but it was separated.  Looks like I restored the wrong version. There's a new version inbound.  I'm testing now.

**Comment by FreelancerJay** [comment] 2022-06-20 04:40
Ahhhh, ok.
I did just update (remove and clean install) to 26 then but no dice still. Error still says it's the same line, despite the large number of line changes in run.sh
I'll just sit back till you mark it as complete :-)

Let me know if you want me to try run anything

**Comment by adamoutler** [comment] 2022-06-20 04:47
There's now something in the cache causing problems.  This is going to need to wait. I recommend linear until this gets fixed.

**Comment by FreelancerJay** [comment] 2022-06-20 04:51
That makes sense. I'll install it again tomorrow or whenever I see other people having better luck.
Lucky for me this happened while my roommate is away, I can just leave it on 100% fans till it's fixed again

**Comment by VikeDragon** [comment] 2022-06-20 05:01
v26a
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- 1a -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Settings initialized. Argon One Detected. Beginning monitor..
/run.sh: line 148: null: unbound variable
Failed 1: value_a=$((100/(tmaxi-tmini)))
Safe Mode Activated!
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by t1gr0u** [comment] 2022-06-20 09:13
I've tried:
* Updated to version 26a
* Reset to default settings
* Hard restart (unplugged the RPi power supply)

But still have the same problem:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 26a
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.6.6
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- 1a -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Settings initialized. Argon One Detected. Beginning monitor..
/run.sh: line 148: null: unbound variable
Failed 1: value_a=$((100/(tmaxi-tmini)))
Safe Mode Activated!
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by romcosha** [comment] 2022-06-20 09:30
The version before is fully functional after restore - 24.1 and version 26a not working.

**Comment by adamoutler** [comment] 2022-06-20 11:44
Fixed by specifying path.  It looks like the older addon was using the scripts for the newer addon instead.

**Comment by adamoutler** [comment] 2022-06-20 11:45
Awaiting verification before closing.

**Comment by t1gr0u** [comment] 2022-06-20 12:04
@adamoutler confirmed for me, seems to be working fine now, thank you for sorting it out 👍 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 26b
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.6.6
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- 1a -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Settings initialized. Argon One Detected. Beginning monitor..
Current Temperature 44 °C
2022-06-20_13:03:03: 44C - Level 1 - Fan 0% (OFF)
```

**Comment by FreelancerJay** [comment] 2022-06-20 12:25
Working here, thanks!

**Comment by VikeDragon** [comment] 2022-06-20 13:05
Everything is wonderful! Thank you for your support! Have a nice day! 
-----------------------------------------------------------
 Add-on: ArgonOne Active Cooling
 Actively keeping your Argon One cool.
-----------------------------------------------------------
 Add-on version: 26b
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.6.6
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Detecting Layout of i2c, we expect to see "1a" here.
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- 1a -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Settings initialized. Argon One Detected. Beginning monitor..
Current Temperature 43 °C
2022-06-20_18:02:50: 43С - Level 1 - Fan 0% (OFF)
Current Temperature 41 °C
Current Temperature 41 °C

**Closed** 2022-06-20 13:23 UTC
